/**
 * bun run fonts
 *
 * Generates assets/fonts.css with the design faces inlined as base64 woff2.
 * The Tauri shell loads the page from disk with no network, so a <link> to
 * Google Fonts silently falls back to system faces there — which changes the
 * whole design. Inlining is the fix.
 *
 * Latin subsets only, and deduplicated by URL: these are variable fonts, so one
 * file serves every weight. Declaring the same file three times would triple
 * the payload for nothing.
 *
 * Outfit is the display face — it carries every title and nothing else, which
 * is why only 500/600 are fetched for it. It is the closest freely
 * redistributable stand-in for the Google Sans Flex the design system asks for
 * and cannot ship: geometric, circular bowls, single-storey 'a'.
 */

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+JP:wght@300;400;500;600" +
  "&family=Source+Sans+3:ital,wght@0,300;0,400;0,600;1,400" +
  "&family=Noto+Sans+JP:wght@400;500;700" +
  "&family=Instrument+Serif:ital@0;1&family=Geist+Mono:wght@400;500&display=swap";

// Google serves different formats per UA; this one gets woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/**
 * Weight is read out of each @font-face block rather than mapped per family.
 *
 * Google emits a range ("100 900") for a variable font and a single value
 * ("400") for a static one, and this set mixes both — Source Sans 3 and Noto
 * Sans JP are variable, IBM Plex Sans JP ships one file per weight. A
 * family-level map would stamp every Plex file with the same weight, and the
 * browser would then pick one arbitrarily for all four.
 */
const WEIGHT_FALLBACK = "400";

/**
 * Metric overrides, the fix for "the text sits low on Windows".
 *
 * Windows resolves a font's vertical metrics from its usWin table, macOS and
 * most Linux stacks from hhea — so the same line box centres differently per
 * platform, and in a 38px pill a couple of pixels reads as misalignment.
 * Overriding ascent/descent in the @font-face pins one set of metrics
 * everywhere; the platform tables stop mattering.
 *
 * The values are chosen so ascent − descent ≈ cap height (~0.72em): with that,
 * flex centring lands the CAP BAND on the geometric centre, which is what the
 * eye reads as "centred" — ink-centring would let descenders drag text high.
 */
const METRICS = "ascent-override:86%;descent-override:14%;line-gap-override:0%";

interface Face {
  family: string;
  style: string;
  weights: Set<string>;
  url: string;
}

/**
 * Collapse the weights seen at one file into what @font-face should declare.
 *
 * A single value stays as it is. Several — which only happens for a variable
 * file — become the "min max" range that spans them, including any range
 * Google already wrote as "100 900".
 */
function weightSpan(weights: Set<string>): string {
  const nums = [...weights].flatMap((w) => w.split(/\s+/)).map(Number).filter(Number.isFinite);
  if (nums.length === 0) return WEIGHT_FALLBACK;
  const lo = Math.min(...nums);
  const hi = Math.max(...nums);
  return lo === hi ? String(lo) : `${lo} ${hi}`;
}

const res = await fetch(CSS_URL, { headers: { "user-agent": UA } });
if (!res.ok) throw new Error(`Google Fonts CSS returned ${res.status}`);
const css = await res.text();

const faces = new Map<string, Face>();
for (const block of css.split("@font-face").slice(1)) {
  const family = /font-family:\s*['"]([^'"]+)['"]/.exec(block)?.[1];
  const style = /font-style:\s*([a-z]+)/.exec(block)?.[1] ?? "normal";
  const weight = /font-weight:\s*([\d ]+)/.exec(block)?.[1]?.trim() ?? WEIGHT_FALLBACK;
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+)/.exec(block)?.[1] ?? "";

  // Keep only the latin subset. The JP families carry full CJK across dozens of
  // subset files and the app has no CJK copy — pulling those in would add
  // megabytes of base64 for glyphs that never render.
  const isLatin = range === "" || range.includes("U+0000-00FF");
  if (!family || !url || !isLatin) continue;

  /* Key by url, and union the weights seen at it.
     For a variable font Google emits one block per weight asked for, all
     pointing at the same file — so the file is one face covering a range, and
     keeping only the first block's weight would declare a 300-only face that
     the browser then synthesises 600 from. A static family gets one entry per
     weight because each really is its own file. */
  const seen = faces.get(url);
  if (seen) seen.weights.add(weight);
  else faces.set(url, { family, style, weights: new Set([weight]), url });
}

if (faces.size === 0) throw new Error("No latin woff2 faces found — did the CSS format change?");

let out =
  "/* GENERATED by scripts/fetch-fonts.ts — do not edit.\n" +
  "   IBM Plex Sans JP / Source Sans 3 / Noto Sans JP / Instrument Serif /\n" +
  "   Geist Mono, latin subsets, inlined so the Tauri shell renders the real\n" +
  "   design with no network.\n\n" +
  "   Source Sans 3 stands in for Acumin Pro and Noto Sans JP for Kozuka Gothic\n" +
  "   Pr6N — both Adobe Fonts, which cannot be self-hosted or embedded. The CSS\n" +
  "   names the Adobe faces first, so a machine with Creative Cloud installed\n" +
  "   uses the real thing and everyone else gets the closest open equivalent by\n" +
  "   the same foundry. */\n";

let raw = 0;
for (const f of faces.values()) {
  const r = await fetch(f.url);
  if (!r.ok) throw new Error(`${f.url} returned ${r.status}`);
  const bytes = new Uint8Array(await r.arrayBuffer());
  raw += bytes.length;
  const b64 = Buffer.from(bytes).toString("base64");
  const weight = weightSpan(f.weights);
  out +=
    `@font-face{font-family:"${f.family}";font-style:${f.style};font-weight:${weight};` +
    `${METRICS};font-display:swap;src:url(data:font/woff2;base64,${b64}) format("woff2")}\n`;
  console.log(`${f.family} ${f.style} ${weight}  ${bytes.length.toLocaleString("en-US")} bytes`);
}

await Bun.write("assets/fonts.css", out);
console.log(
  `\n${faces.size} faces · ${raw.toLocaleString("en-US")} bytes woff2 → ` +
    `assets/fonts.css ${out.length.toLocaleString("en-US")} bytes`,
);
