/**
 * bun run fonts
 *
 * Generates assets/fonts.css with the three design faces inlined as base64
 * woff2. The Tauri shell loads the page from disk with no network, so a
 * <link> to Google Fonts silently falls back to system faces there — which
 * changes the whole design. Inlining is the fix.
 *
 * Latin subsets only, and deduplicated by URL: Instrument Sans and Geist Mono
 * are variable fonts, so one file serves every weight. Declaring the same file
 * three times would triple the payload for nothing.
 */

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400;0,500;0,600;1,400" +
  "&family=Instrument+Serif:ital@0;1&family=Geist+Mono:wght@400;500&display=swap";

// Google serves different formats per UA; this one gets woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/** Weight range to declare per family — these are variable fonts. */
const WEIGHTS: Record<string, string> = {
  "Instrument Sans": "400 600",
  "Instrument Serif": "400",
  "Geist Mono": "400 500",
};

interface Face {
  family: string;
  style: string;
  url: string;
}

const res = await fetch(CSS_URL, { headers: { "user-agent": UA } });
if (!res.ok) throw new Error(`Google Fonts CSS returned ${res.status}`);
const css = await res.text();

const faces = new Map<string, Face>();
for (const block of css.split("@font-face").slice(1)) {
  const family = /font-family:\s*['"]([^'"]+)['"]/.exec(block)?.[1];
  const style = /font-style:\s*([a-z]+)/.exec(block)?.[1] ?? "normal";
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+)/.exec(block)?.[1] ?? "";

  // Keep only the latin subset — the app has no CJK or Cyrillic copy.
  const isLatin = range === "" || range.includes("U+0000-00FF");
  if (!family || !url || !isLatin) continue;

  // Key by url: one variable file covers every weight of that family/style.
  if (!faces.has(url)) faces.set(url, { family, style, url });
}

if (faces.size === 0) throw new Error("No latin woff2 faces found — did the CSS format change?");

let out =
  "/* GENERATED by scripts/fetch-fonts.ts — do not edit.\n" +
  "   Instrument Sans / Instrument Serif / Geist Mono, latin subsets, inlined so\n" +
  "   the Tauri shell renders the real design with no network. */\n";

let raw = 0;
for (const f of faces.values()) {
  const r = await fetch(f.url);
  if (!r.ok) throw new Error(`${f.url} returned ${r.status}`);
  const bytes = new Uint8Array(await r.arrayBuffer());
  raw += bytes.length;
  const b64 = Buffer.from(bytes).toString("base64");
  const weight = WEIGHTS[f.family] ?? "400";
  out +=
    `@font-face{font-family:"${f.family}";font-style:${f.style};font-weight:${weight};` +
    `font-display:swap;src:url(data:font/woff2;base64,${b64}) format("woff2")}\n`;
  console.log(`${f.family} ${f.style} ${weight}  ${bytes.length.toLocaleString("en-US")} bytes`);
}

await Bun.write("assets/fonts.css", out);
console.log(
  `\n${faces.size} faces · ${raw.toLocaleString("en-US")} bytes woff2 → ` +
    `assets/fonts.css ${out.length.toLocaleString("en-US")} bytes`,
);
